---
output: pdf_document
---

### Figure 6

```{r alexander6}
sfi_plot_unlist(sfi_plot(author = "alexander", figure = "6"))
```

### Figure 7

```{r alexander7}
sfi_plot_unlist(sfi_plot(author = "alexander", figure = "7"))
```



ewpage


## Feldman

### Figure 1

```{r feldman1}
sfi_plot_unlist(sfi_plot(author = "feldman", figure = "1"))
```

### Figure 2

```{r feldman2}
sfi_plot_unlist(sfi_plot(author = "feldman", figure = "2"))
```

### Figure 2

```{r frankenreiter2}
sfi_plot_unlist(sfi_plot(author = "frankenreiter", figure = "2"))
```

### Figure 3

```{r frankenreiter3}
sfi_plot_unlist(sfi_plot(author = "frankenreiter", figure = "3"))
```

### Figure 4

```{r frankenreiter4}
sfi_plot_unlist(sfi_plot(author = "frankenreiter", figure = "4"))
```

### Figure 5.1

```{r frankenreiter5_1}
sfi_plot_unlist(sfi_plot(author = "frankenreiter", figure = "5_1"))
```

### Figure 5.2

```{r frankenreiter5_2}
sfi_plot_unlist(sfi_plot(author = "frankenreiter", figure = "5_2"))
```

### Figure 6.1

```{r frankenreiter6_1}
sfi_plot_unlist(sfi_plot(author = "frankenreiter", figure = "6_1"))
```

### Figure 6.2

```{r frankenreiter6_2}
sfi_plot_unlist(sfi_plot(author = "frankenreiter", figure = "6_2"))
```



ewpage


## Laquer

### Figure 1

```{r laquer1}
sfi_plot_unlist(sfi_plot(author = "laquer", figure = "1"))
```

### Figure 2

```{r laquer2}
sfi_plot_unlist(sfi_plot(author = "laquer", figure = "2"))
```



ewpage


## Livemore

### Figure 1

```{r livemore1}
sfi_plot_unlist(sfi_plot(author = "livemore", figure = "1"))
```


