---
title: "Chen and Ash"
subtitle: "Figures"
date: 'Oct 19th 2018'
output: 
  pdf_document:
    latex_engine: xelatex
    includes:
      in_header: preamble.sty
fig_width: 4
fig_height: 2.6
bibliography: bibliography.bib
---


```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, error= FALSE, cache = FALSE}
# Packages
library(sfi)
library(webshot)
library(ggplot2)
library(dplyr)
library(plotly)
library(ggiraph)
library(scales)
library(tidyverse)
library(knitr)
library(Hmisc)
library(RColorBrewer)
library(extrafont)
library(kableExtra)
library(grid)

# webshot::install_phantomjs()

loadfonts()
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
            cache=FALSE,
              prompt=FALSE,
              tidy=TRUE,
              comment=NA,
              message=FALSE,
              warning=FALSE,
              dpi = 300,
              # dev = "cairo_pdf",
              dev = c("png", "cairo_pdf"),
              fig.pos="!h",
              fig.path = 'figures/')
opts_knit$set(width=75)
options(xtable.comment = FALSE)
```


#### This markdown is for Chen and Ash figures.

\newpage


# Chen and Ash 1 (version 1)

```{r, fig.width = 4, fig.height = 7.25}
# # no scientific notation
  # options(scipen = '999')
  # 
  # # get data 
  data <- all_data$chen$f1
  
  # get label numbers
  data$text_label <- unlist(lapply(strsplit(data$circuit, '-', fixed = TRUE), function(x) x[length(x)]))
  
  # remove 11 with FC and SC with 12, and 0 with dc
  data$text_label <- gsub('^0$', 'DC', data$text_label)
  data$text_label <- gsub('12', 'FC', data$text_label)

  # 
  # version 11
  g1 <- ggplot(data,
               aes(x = x,
                   y = y)) +
    geom_text(aes(label = text_label),
              size = 2,
              alpha = 0.6,
              color = 'black') +
    labs(x = '',
         y = '',
         title = 'Figure 1: Centered by Topic-Year, Averaged by Judge, Labeled by Court',
         subtitle = 'Circuit, CC Judge Vector, Demeaned by Year and Big Topic',
         caption = '') +
    theme_sfi(lp = 'none',
              y_axis_title_style = 'bold',
              x_axis_title_style = 'bold',
              title_style = 'bold') +
        theme(axis.text=element_text(size = 10, hjust = 1))

  
  g1

```

# Chen and Ash 1 (version 2)

```{r, fig.width = 4, fig.height = 7.25}
# # no scientific notation
  # options(scipen = '999')
  # 
  # # get data 
  data <- all_data$chen$f1
  
  # get label numbers
  data$text_label <- unlist(lapply(strsplit(data$circuit, '-', fixed = TRUE), function(x) x[length(x)]))
  
  # remove 11 with FC and SC with 12, and 0 with dc
  data$text_label <- gsub('^0$', 'DC', data$text_label)
  data$text_label <- gsub('12', 'FC', data$text_label)

  # 
  # version 11
  g1 <- ggplot(data,
               aes(x = x,
                   y = y)) +
    geom_text(aes(label = text_label),
              size = 3,
              alpha = 0.4,
              color = 'black') +
    labs(x = '',
         y = '',
         title = 'Figure 1: Centered by Topic-Year, Averaged by Judge, Labeled by Court',
         subtitle = 'Circuit, CC Judge Vector, Demeaned by Year and Big Topic',
         caption = '') +
    theme_sfi(lp = 'none',
              y_axis_title_style = 'bold',
              x_axis_title_style = 'bold',
              title_style = 'bold') +     
    theme(axis.text=element_text(size = 10, hjust = 1))

  
  g1

```


# Chen and Ash 2 (version 1)

```{r, fig.width = 4, fig.height = 7.25}
# # get data 
  data <- all_data$chen$f2
  
  
  # version 11
  g1 <- ggplot(data,
               aes(x = x,
                   y = y)) +
    ylim(c(-7, 18)) +
    geom_text(aes(label = `decade-s`),
              size = 2,
              alpha = 0.6,
              color = 'black') +
    labs(x = '',
         y = '',
         title = 'Figure 2.',
         subtitle = 'Centered by Court Topic, Averaged by Court-Year, Labeled by Decade',
         caption = 'Court Decade, SC & CC Court Decade Vector, Demeaned by Circuit and Big Topic') +
    theme_sfi(lp = 'none',
              y_axis_title_style = 'bold',
              x_axis_title_style = 'bold',
              title_style = 'bold') +
        theme(axis.text=element_text(size = 10, hjust = 1))
  

  g1

```



# Chen and Ash 2 (version 2)

```{r, fig.width = 4, fig.height = 7.25}
  # version 11
   # get data 
  data <- all_data$chen$f2
  
  g2 <- ggplot(data,
               aes(x = x,
                   y = y)) +
    geom_text(aes(label = `decade-s`),
              size = 2,
              alpha = 0.6,
              color = 'black') +
    stat_ellipse(aes(x, y,color= `decade-s`),type = "norm", size = 0.3, alpha = 1) +
    scale_color_manual(name = 'Confidence elipse',
                       values = c('darkgrey','darkgrey', 'darkgrey','darkgrey','darkgrey','darkgrey',
                                  'darkgrey','darkgrey','darkgrey','darkgrey','darkgrey','darkgrey','darkgrey')) +
    labs(x = '',
         y = '',
         title = 'Figure 2.',
         subtitle = 'Centered by Court Topic, Averaged by Court-Year, Labeled by Decade',
         caption = 'Court Decade, SC & CC Court Decade Vector, Demeaned by Circuit and Big Topic') +
    theme_sfi(lp = 'none',
              y_axis_title_style = 'bold',
              x_axis_title_style = 'bold',
              title_style = 'bold') +
        theme(axis.text=element_text(size = 10, hjust = 1))

  g2

```


# Chen and Ash 3 (version 1)

```{r, fig.width = 4, fig.height = 7.25}
# # no scientific notation
  # options(scipen = '999')
  # 
  # # get data 
  data <- all_data$chen$f3
  names(data) <- gsub('-', '.', names(data), fixed = TRUE)
  
  data <- data[data$big.issue != 'Others',]
  data <- data[data$big.issue != '9',]
  data$big.issue <- as.factor(data$big.issue)
  JY_levels <- levels(data$big.issue)
  JY_labels <- c('1 - Criminal Appeal', '2 - Civil Rights', '3 - First Amendment','4 - Due Process',
                 '5 - Privacy', '6 - Labor','7 - Regulation')
  JY_labels_n <- c('1', '2', '3','4','5', '6','7')
  data$big.issue.n <- data$big.issue
  data$big.issue  <- factor(data$big.issue, levels=JY_levels, labels=JY_labels)
  
  
  data$big.issue.n  <- factor(data$big.issue.n, levels=JY_levels, labels=JY_labels_n)
  
  # # remove 9 and others
  # data <- data %>% filter(`big-issue` != '9') %>%
  #   filter(`big-issue` != 'Others')
  # 
  # Y_labels <- c('1 - Criminal Appeal', '2 - Civil Rights', '3 - First Amendment','4 - Due Process',
  #               '5 - Privacy', '6 - Labor','7 - Regulation','9 - Miscellaneous', 'Others')
  # JY_labels_n <- c('1', '2', '3','4','5', '6','7','9', 'Others')
  # 
  # 
  # version 11
  g1 <- ggplot(data,
               aes(x = x,
                   y = y)) +
    geom_text(aes(label = `big.issue.n`),
               size = 2,
               color = 'black',
               alpha = 0.4) +
    stat_ellipse(aes(x, y,color= `big.issue.n`),type = "norm", size = 0.5,alpha = 1) +
    scale_color_manual(name = 'Confidence elipse',
                       values = c('darkgrey','darkgrey', 'darkgrey','darkgrey','darkgrey','darkgrey',
                                  'darkgrey','darkgrey','darkgrey','darkgrey','darkgrey','darkgrey','darkgrey')) +
    labs(x = '',
         y = '',
         title = 'Figure 3.',
         subtitle = 'Centered by Judge-Year, Averaged by Topic-Year, Labeled by Topic',
         caption = paste0('Big Topics and Year, SC and CC Topic Year Vector, Demeaned by Judge & Year', 
                          '\n',
                          '*Ellipses represent a confidence measurement for the clusters')) +
  annotate(geom = 'text',
           x = 0,
           y = -50,
           family = 'CMU Bright',
           label = 'Regulation') +
    annotate(geom = 'text',
            family = 'CMU Bright', 
             x = 0,
             y = 50,
             label = 'Criminal Appeal') +
    annotate(geom = 'text',
             family = 'CMU Bright', 
             x = -38,
             y = -19,
             label = '1st Amendment') +
    annotate(geom = 'text',
             family = 'CMU Bright',
             x = -40,
             y = 28,
             label = 'Civil Rights') + 
    annotate(geom = 'text',
             family = 'CMU Bright',
             x = 17,
             y = 31,
             label = 'Privacy') +
    annotate(geom = 'text',
             family = 'CMU Bright',
             x = 38,
             y = 13,
             label = 'Labor') +
    annotate(geom = 'text',
             family = 'CMU Bright',
             x = 30,
             y = -2,
             label = 'Due Process') +
    theme_sfi(lp = 'none',
              y_axis_title_style = 'bold',
              x_axis_title_style = 'bold',
              title_style = 'bold') +
        theme(axis.text=element_text(size = 10, hjust = 1))
   g1 
  
  

```



# Chen and Ash 3 (version 2)

```{r, fig.width = 4, fig.height = 7.25}

# # get data 
  data <- all_data$chen$f3
  names(data) <- gsub('-', '.', names(data), fixed = TRUE)
  
  data <- data[data$big.issue != 'Others',]
  data <- data[data$big.issue != '9',]
  data$big.issue <- as.factor(data$big.issue)
  JY_levels <- levels(data$big.issue)
  JY_labels <- c('1 - Criminal Appeal', '2 - Civil Rights', '3 - First Amendment','4 - Due Process',
                 '5 - Privacy', '6 - Labor','7 - Regulation')
  JY_labels_n <- c('1', '2', '3','4','5', '6','7')
  data$big.issue.n <- data$big.issue
  data$big.issue  <- factor(data$big.issue, levels=JY_levels, labels=JY_labels)

  data$big.issue.n  <- factor(data$big.issue.n, levels=JY_levels, labels=JY_labels_n)
  
  g2 <- ggplot(data,
               aes(x = x,
                   y = y)) +
    geom_text(aes(label = `big.issue.n`),
              size = 2,
              color = 'black',
              alpha = 0.4) +
    labs(x = '',
         y = '',
         title = 'Figure 3.',
         subtitle = 'Centered by Judge-Year, Averaged by Topic-Year, Labeled by Topic',
         caption = paste0('Big Topics and Year, SC and CC Topic Year Vector, Demeaned by Judge & Year', 
                          '\n',
                          '*Ellipses represent a confidence measurement for the clusters')) +
    theme_sfi(lp = 'none',
              y_axis_title_style = 'bold',
              x_axis_title_style = 'bold',
              title_style = 'bold') +
    annotate(geom = 'text',
           x = 0,
           y = -50,
           family = 'CMU Bright',
           label = 'Regulation') +
    annotate(geom = 'text',
            family = 'CMU Bright', 
             x = 0,
             y = 50,
             label = 'Criminal Appeal') +
    annotate(geom = 'text',
             family = 'CMU Bright', 
             x = -38,
             y = -19,
             label = '1st Amendment') +
    annotate(geom = 'text',
             family = 'CMU Bright',
             x = -40,
             y = 28,
             label = 'Civil Rights') + 
    annotate(geom = 'text',
             family = 'CMU Bright',
             x = 17,
             y = 31,
             label = 'Privacy') +
    annotate(geom = 'text',
             family = 'CMU Bright',
             x = 38,
             y = 13,
             label = 'Labor') +
    annotate(geom = 'text',
             family = 'CMU Bright',
             x = 30,
             y = -2,
             label = 'Due Process') +
        theme(axis.text=element_text(size = 10, hjust = 1))
  
g2

```


# Chen and Ash 4 (version 1)

```{r, fig.width = 4, fig.height = 7.25}
# # get data 
  data <- all_data$chen$f4
  
  # recode party affiliation
  data <- data[data$party %in% c(1,0),]
  data$party <- ifelse(data$party == 0, 'R', 'D')
  
  # 
  # version 11
  g1 <- ggplot(data,
               aes(x = x,
                   y = y,
                   label = party,
                   color = party)) +
    geom_point(size = 0, 
               alpha = 0) +
    geom_text(size = 2,
              alpha = 0.6,
              show.legend = FALSE) +
    scale_color_manual(name = 'Party affiliation',
                       values = c('black', '#4F4F4F'),
                       breaks = c('D', 'R'),
                       labels = c('D = Democrat', 'R = Republican')) +
      guides(label = guide_legend(override.aes = list(text = 0)),
             color = guide_legend(override.aes = list(text = 0))) +
    labs(x = '',
         y = '',
         title = 'Figure 4.',
         subtitle = 'Centered by Court-Topic-Year, Averaged by Judge, Labeled by Political Party',
         caption = 'Party affiliation, SC & CC Judge Vector, Demeaned by Circuit, Big Topics, and year') +
    theme_sfi(lp = 'bottom',
              y_axis_title_style = 'bold',
              x_axis_title_style = 'bold',
              title_style = 'bold') +
        theme(axis.text=element_text(size = 10, hjust = 1))
  
  
 g1
  

```



# Chen and Ash 4 (version 2)

```{r, fig.width = 4, fig.height = 7.25}
 # get data 
  data <- all_data$chen$f4
  
  # recode party affiliation
  data <- data[data$party %in% c(1,0),]
  data$party <- ifelse(data$party == 0, 'R', 'D')
  
 
  g2 <- ggplot(data,
               aes(x = x,
                   y = y,
                   color = party)) +
    geom_point(size = 2, 
               alpha = 0.5) +
    scale_color_manual(name = 'Party affiliation',
                       values = c('black', 'darkgrey'),
                       labels = c('Democrat', 'Republican')) +
    guides(label = guide_legend(override.aes = list(text = 0)),
           color = guide_legend(override.aes = list(text = 0))) +
    labs(x = '',
         y = '',
         title = 'Figure 4.',
         subtitle = 'Centered by Court-Topic-Year, Averaged by Judge, Labeled by Political Party',
         caption = 'Party affiliation, SC & CC Judge Vector, Demeaned by Circuit, Big Topics, and year') +
    theme_sfi(lp = 'bottom',
              y_axis_title_style = 'bold',
              x_axis_title_style = 'bold',
              title_style = 'bold') +
        theme(axis.text=element_text(size = 10, hjust = 1))
g2

```
